/**
 * WhatsApp sharing utilities for invoices and tax reports
 */

export const shareViaWhatsApp = (text: string, phoneNumber?: string) => {
  const encoded = encodeURIComponent(text);
  const url = phoneNumber
    ? `https://wa.me/${phoneNumber.replace(/\D/g, '')}?text=${encoded}`
    : `https://wa.me/?text=${encoded}`;
  window.open(url, '_blank');
};

export const shareInvoiceViaWhatsApp = (invoice: {
  invoiceNumber: string;
  businessName: string;
  clientName: string;
  total: number;
  dueDate: string;
  currency?: string;
  paymentDetails?: {
    bankName?: string;
    accountName?: string;
    accountNumber?: string;
  };
}) => {
  const currencySymbol = invoice.currency === 'USD' ? '$' : invoice.currency === 'GBP' ? '£' : invoice.currency === 'EUR' ? '€' : '₦';
  const formattedTotal = `${currencySymbol}${invoice.total.toLocaleString('en-NG', { minimumFractionDigits: 2 })}`;

  let message = `📄 *INVOICE ${invoice.invoiceNumber}*\n\n`;
  message += `From: *${invoice.businessName}*\n`;
  message += `To: *${invoice.clientName}*\n`;
  message += `Amount Due: *${formattedTotal}*\n`;
  message += `Due Date: ${invoice.dueDate}\n`;

  if (invoice.paymentDetails?.bankName) {
    message += `\n💳 *Payment Details:*\n`;
    message += `Bank: ${invoice.paymentDetails.bankName}\n`;
    if (invoice.paymentDetails.accountName) message += `Account: ${invoice.paymentDetails.accountName}\n`;
    if (invoice.paymentDetails.accountNumber) message += `Acc No: ${invoice.paymentDetails.accountNumber}\n`;
  }

  message += `\n_Sent via Nigeria Tax Companion_`;

  shareViaWhatsApp(message);
};

export const shareTaxReportViaWhatsApp = (report: {
  title: string;
  period: string;
  summary: string;
}) => {
  let message = `📊 *${report.title}*\n`;
  message += `Period: ${report.period}\n\n`;
  message += report.summary;
  message += `\n\n_Generated by Nigeria Tax Companion_`;

  shareViaWhatsApp(message);
};
